spring.application.name=fraud-payment-service

#Razorpay configuration
razorpay.key-id=
razorpay.key-secret=




server.port =8083

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/payment-service
spring.datasource.username=postgres
spring.datasource.password=Ketan@123

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional
spring.kafka.listener.missing-topics-fatal=false

#Actuator

management.endpoints.web.exposure.include=health,info